"use client"

import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React, {ReactNode} from "react";
import {Auth0Provider, useAuth0} from "@auth0/auth0-react";

const inter = Inter({subsets: ["latin"]});

const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export function AuthGuard({children}: Readonly<{ children: ReactNode }>) {
    const {isLoading, isAuthenticated, error, loginWithRedirect} = useAuth0();
    return (
        <div>
            {isLoading && <div>Loading...</div>}
            {error && <div>Oops... {error.message}</div>}
            {
                !isAuthenticated && !isLoading &&
                <button onClick={() => loginWithRedirect()}>
                    Log in
                </button>
            }
            {
                isAuthenticated && !isLoading && !error &&
                children
            }
        </div>
    );
}

export default function RootLayout({children,}: Readonly<{ children: ReactNode; }>) {
    const {NEXT_PUBLIC_AUTH0_DOMAIN, NEXT_PUBLIC_AUTH0_CLIENT_ID} = process.env;
    return (
        <html lang="en">
        <body className={inter.className}>
        <Auth0Provider clientId={NEXT_PUBLIC_AUTH0_CLIENT_ID!} domain={NEXT_PUBLIC_AUTH0_DOMAIN!}>
            <AuthGuard>
            {children}
            </AuthGuard>
        </Auth0Provider>
        </body>
        </html>
    );
}
